name: iCoLand
main: me.slaps.iCoLand.iCoLand
version: v2.40
author: magik
depend: [ iConomy, Permissions ]
description: >
             A protection plugin based on a block purchasing for money scheme.
commands:
    icl:
        description: the main iConomyLand command
        usage: |
               /<command>
               /<command> help <topic>
    icoland:
        description: the main iConomyLand command
        usage: |
               /<command>
               /<command> help <topic>
